name: restart workflow
on:
  repository_dispatch:
    types: [restart]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: restart workflow
        run: |
          URL=https://api.github.com/repos/${{github.repository}}/actions/runs/${{ github.event.client_payload.runid }}/rerun
          curl -X POST -u "weide-zhou:${{secrets.ACTIONS_PAT}}" $URL